Use nhost dashboard with optional "--dashboard" flag
nhost/cli pull request #452
Opened 2022-11-22 12:31 UTC by elephant3

## Description
Plug [nhost dashboard](https://github.com/nhost/nhost/tree/main/dashboard) into CLI

2022-11-22 13:00 UTC, elitan commented
Since we plan to make the Nhost Dashboard the default UI (instead of Hasura Console), does it make sense to remove or rename this flag?

Random idea: Maybe `--ui=nhost` and `--ui=hasura` is default?

2022-11-22 13:11 UTC, elephant3 commented
> Since we plan to make the Nhost Dashboard the default UI (instead of Hasura Console), does it make sense to remove or rename this flag?
> 
> Once the Nhost Dashboard is the default UI this `--dashboard` flag wouldn't make much sense.
> 
> Random idea: Maybe `--ui=nhost` and `--ui=hasura` is default?

Sounds good

2022-11-23 06:22 UTC, elitan commented
@nunopato What do you think?

2022-11-25 09:02 UTC, elephant3 commented
Updated, now `--ui nhost` shall be provided for our dashboard

2022-11-25 09:44 UTC, elitan requested changes
Small copy updates.

2022-11-25 09:44 UTC, elitan commented on README.md
> +- [Dashboard](https://github.com/nhost/nhost/tree/main/dashboard)
```suggestion
- [Nhost Dashboard](https://github.com/nhost/nhost/tree/main/dashboard)
```

2022-11-25 09:44 UTC, elitan commented on README.md
> +You can also use our new dashboard:
```suggestion
You can also use the Nhost Dashboard:
```

2022-11-25 09:44 UTC, elitan commented on nhost/service/endpoints.go
> +- Dashboard:		%s
```suggestion
- Nhost Dashboard:		%s
```

2022-11-25 09:44 UTC, elitan commented on nhost/service/endpoints.go
>  - Hasura console:	%s
```suggestion
- Hasura Console:	%s
```

2022-11-25 09:50 UTC, elitan approved these changes

2022-11-25 09:54 UTC, merged